### ISSUE TITLE
Readme.md file is empty

### ISSUE THREAD

**Issue by pavansw1** [pavansw/demoAccentureSlovakia#1]
Hello dear developers, 
This not at all good to have empty Readme file. 
**Team leader have a look to it.** @pavansw

**Comment by pavansw1** [comment]
@pavansw1 
Sorry for the empty file.
But you didnt asked to write it yesterday. No worries I will ask Monika to do this.
**@bucholcerova Kindly look into this**

**Comment by JozoNL** [comment]
issue resolved

**Comment by pavansw1** [comment]
@AlexFilova @DianaComan 
Take care next time...:)
